services:
  postgres:
    image: postgres:16-alpine
    container_name: la-bidder-postgres
    environment:
      POSTGRES_USER: labidder
      POSTGRES_PASSWORD: labidder_pass
      POSTGRES_DB: labidder
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U labidder']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: la-bidder-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@labidder.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
